image: docker:19.03.0

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"

services:
    - docker:19.03.0-dind

stages:
    - test
    - build
    - tag

lint:
    stage: test
    tags:
        - docker
    script:
        - apk update && apk add bash git
        - bash run_static_analysis.sh
    except:
        - /-backup$/
        - /-wip$/

unit test:
    stage: test
    tags:
        - docker
    script:
        - apk update && apk add bash
        - bash run_unit_tests.sh
    except:
        - /-backup$/
        - /-wip$/

build:
    stage: build
    tags:
        - docker
    script:
        - apk update && apk add bash git
        - bash scripts/ci-build.sh
    except:
        - /-backup$/
        - /-wip$/

tag:
    stage: tag
    tags:
        - docker
    script:
        - apk update && apk add bash git
        - bash scripts/ci-tag.sh
    only:
        - /^master$/
