image: docker:19.03.0

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"

services:
    - docker:19.03.0-dind

stages:
    - lint
    - build

lint:
    stage: lint
    tags:
        - docker
    script:
        - apk update && apk add bash git
        - bash run_static_analysis.sh
    except:
        - /-backup$/
        - /-wip$/

build:
    stage: build
    tags:
        - docker
    script:
        - apk update && apk add bash git
        - bash scripts/ci-build.sh
    except:
        - /-backup$/
        - /-wip$/
