name: Data import service


on:
  release:
    types: 
      - published


env:
  CI: true
  DOCKER_USER: ${{ github.actor }}
  DOCKER_PASS: ${{ secrets.GHCR_TOKEN }}
  DOCKER_REG: ghcr.io
  GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}


jobs:

  build:
    name: Build release image
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    outputs:
      GENERATED_IMAGE_NAME: ${{ steps.build_img.outputs.GENERATED_IMAGE_NAME }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GHCR_TOKEN }}
          fetch-depth: 0
          
      - name: Build image
        id: build_img
        run: make build-docker args="-t"
