port: 80
TLSPort: 443
allowDirectoryIndex: true
# @todo rmeove certs
certFile: /etc/spa-server/certs/spa-server.pem
keyFile: /etc/spa-server/certs/spa-server.key
sitesAvailable:
  - path: "/var/www/html"
    index: "index.html"
    host: "{subdomain:(?:www.)?}localhost"
    certFile: /etc/spa-server/certs/spa-server.pem
    keyFile: /etc/spa-server/certs/spa-server.key
    redirectNonTLS: true
  - path: "/var/www/html/spa2/"
    index: "index.html"
    host: "127.0.0.1"
