port: 80
TLSPort: 443
allowDirectoryIndex: true
sitesAvailable:
  - path: "/var/www/html"
    index: "index.html"
    host: "{subdomain:(?:www.)?}localhost"
    certFile: /etc/spa-server/certs/spa-server.pem
    keyFile: /etc/spa-server/certs/spa-server.key
    redirectNonTLS: true
    compress: true
  - path: "/var/www/html/spa2/"
    index: "index.html"
    host: "127.0.0.1"
